### ISSUE TITLE
Merge Release Packages: Default behaviour for package metadata

### ISSUE THREAD

**Issue by duncandewhurst** [open-contracting/ocdskit-web#22]
Currently the merge release packages tool generates invalid data because `publishedDate` is set to `""`, even when submitting a single release package to the tool.

When a single release package is submitted, we can just copy the package metadata values from the source file to the result file.

When multiple release packages are submitted, we should agree a sensible default for how to populate each package metadata field and make sure this is explained in the tool's UI.

**Comment by jpmckinney** [comment]
The default can be the present time. We can provide a text box to pass as the `--published-date` option in OCDS Kit. Note that the (unreleased) OCDS Kit 0.1.0 now has library methods, so that ocdskit-web doesn't have to use the CLI code path.
